CREATE TABLE Coffees (id INTEGER PRIMARY KEY AUTOINCREMENT, user_card_id VARCHAR(255), date DATETIME DEFAULT CURRENT_TIMESTAMP, unit_price DECIMAL(5,2));
CREATE TABLE Users (card_id VARCHAR(255) PRIMARY KEY, name VARCHAR(255));
CREATE TABLE Payments (id INTEGER PRIMARY KEY AUTOINCREMENT, user_card_id VARCHAR(255), date DATETIME DEFAULT CURRENT_TIMESTAMP, amount DECIMAL(5,2));

